import Script from "next/script";
import dotenv from "dotenv";
import "../app/globals.css";

dotenv.config();
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function App({ Component, props }) {
  return (
    <>
      <Script src="https://www.google.com/recaptcha/api.js"></Script>
      <Script src={`https://www.google.com/recaptcha/api.js?render=${process.env.SITE_KEY}`}/>
      <Component {...props} />
    </>
  )
}
